# ######################################################################################################################
#
#              """          docker-compose.yml
#       -\-    _|__
#        |\___/  . \        Created on 13 Aug. 2024 at 14:39
#        \     /(((/        by hmelica
#         \___/)))/         hmelica@student.42.fr
#
# ######################################################################################################################

services:
  django:
    container_name: django
    volumes:
      - site:/usr/src/app
    networks:
      - transcendance
    env_file: .env
    environment:
      NAME: "django_site"
    restart: unless-stopped
    build:
      context: ./requirements/django
    expose:
      - ${INTERNAL_DJANGO_PORT}

  nginx:
    env_file: .env
    container_name: nginx
    networks:
      - transcendance
    # volumes:
    #   - static:/usr/share/nginx/html
    build:
      context: ./requirements/nginx
    ports:
      - ${EXTERNAL_NGINX_PORT}:${SITE_PORT}
    restart: on-failure

volumes:
  site:
    name: site
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../site'
  static:
    name: static
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../static'

networks:
  transcendance:
