# ######################################################################################################################
#
#              """          docker-compose.yml
#       -\-    _|__
#        |\___/  . \        Created on 13 Aug. 2024 at 14:39
#        \     /(((/        by hmelica
#         \___/)))/         hmelica@student.42.fr
#
# ######################################################################################################################

services:
  django:
    container_name: django
    volumes:
      - site:/usr/src/app
    networks:
      - transcendance
    env_file: .env
    environment:
      NAME: "django_site"
    restart: unless-stopped
    build:
      context: ./requirements/django
    expose:
      - ${INTERNAL_DJANGO_PORT}

  frontend:
    container_name: frontend
    env_file: .env
    networks:
        - transcendance
    expose:
      - ${INTERNAL_FRONTEND_PORT}
    build:
      context: ./requirements/frontend/
    restart: unless-stopped

  nginx:
    env_file: .env
    container_name: nginx
    networks:
      - transcendance
    # volumes:
    #   - static:/usr/share/nginx/html
    build:
      context: ./requirements/nginx
    ports:
      - ${EXTERNAL_NGINX_PORT}:${SITE_PORT}
    restart: on-failure

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./requirements/elasticsearch
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - ${ELASTICSEARCH_PORT}
    ports:
      - ${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: ./requirements/logstash
      dockerfile: Dockerfile.logstash
    expose:
      - ${BEATS_PORT}
      - ${INTERNAL_LOGSTASH_PORT}
    ports:
      - ${BEATS_PORT}:${BEATS_PORT}
      - ${INTERNAL_LOGSTASH_PORT}:${INTERNAL_LOGSTASH_PORT}
    volumes:
      - ./requirements/logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    container_name: kibana
    build:
      context: ./requirements/kibana
      dockerfile: Dockerfile.kibana
    expose:
      - ${EXTERNAL_KIBANA_PORT}
    ports:
      - ${EXTERNAL_KIBANA_PORT}:${EXTERNAL_KIBANA_PORT}
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  site:
    name: site
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../site'
  static:
    name: static
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../static'
  es_data:
    name: es_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../es_data'

networks:
  transcendance:
  elk:
    driver: bridge
