FROM nginx

RUN apt-get update \
    && apt-get install -y openssl less netcat-openbsd curl iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY ./tools /build

RUN bash /build/init.sh \
    && rm -rf /build/init.sh

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY templates/* /etc/nginx/templates/

COPY static/* /usr/share/nginx/html/

# ENTRYPOINT nginx-debug -g 'daemon off;' 